# Generated by Django 4.2 on 2023-05-27 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_course_exercice_grade_material_module_question_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=150)),
                ('created_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='course',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='exercice',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='exercice',
            name='mark_allocation',
            field=models.CharField(default='20', max_length=50),
        ),
        migrations.AddField(
            model_name='exercice',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='exercice',
            name='type',
            field=models.CharField(default='test', max_length=50),
        ),
        migrations.AddField(
            model_name='grade',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='grade',
            name='master',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.teacher'),
        ),
        migrations.AddField(
            model_name='grade',
            name='name',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='material',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='material',
            name='link',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='material',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='question',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='question',
            name='exercice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.exercice'),
        ),
        migrations.AddField(
            model_name='question',
            name='response',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='question',
            name='statement',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='question',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.teacher'),
        ),
        migrations.AddField(
            model_name='student',
            name='phone_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student_question',
            name='answer',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student_question',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='student_question',
            name='mark',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.teacher'),
        ),
        migrations.AlterField(
            model_name='exercice',
            name='mark',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='student_question',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.question'),
        ),
        migrations.AlterField(
            model_name='student_question',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.student'),
        ),
        migrations.DeleteModel(
            name='Module',
        ),
        migrations.AddField(
            model_name='part',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.course'),
        ),
        migrations.AddField(
            model_name='exercice',
            name='part',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.part'),
        ),
        migrations.AddField(
            model_name='material',
            name='part',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.part'),
        ),
    ]
